= Asciidoctor + Reveal.js Slides Preview Tool

This tool can be used to quickly preview slides created with Asciidoctor and Reveal.js.

== Asciidoctor Slides Infrastructure

The following projects are part of the Asciidoctor Slides infrastructure:

* https://github.com/vshn/asciidoctor-slides[Generator] encapsulating a Node.js application driving the creation of the `slides.html` HTML file
* https://github.com/vshn/asciidoctor-slides-cookiecutter[Cookiecutter] offering a simple mechanism to generate new presentation slide projects
* https://github.com/vshn/asciidoctor-slides-preview[Preview] allowing the live preview of slides on `localhost:2020` (this project)
* https://github.com/vshn/asciidoctor-slides-notes-exporter[Speaker Notes Exporter] to export speaker notes

== How to use

Run the following command on top of any project containing Asciidoctor + Reveal.js slides:

[source,bash]
--
docker run --user "$(id -u)" --rm --publish 35729:35729 --publish 2020:2020 --volume "${PWD}":/build vshn/slides-preview:$VERSION
--

Open the URL http://localhost:2020 to see the slides.

== LiveReload

This image is capable of "live reloading" the slides as the user writes the Asciidoc source. To do that, you need a browser with one of these extensions:

* https://addons.mozilla.org/en-US/firefox/addon/livereload-web-extension/[Firefox]
* https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei[Google Chrome]

Open the documentation in your browser and click on the LiveReload extension button on the toolbar; when it becomes green, the browser will automatically refresh whenever you save the Asciidoc file.

